### ISSUE TITLE
Keep a log

### ISSUE THREAD

**Issue by regeto** [regeto/comics-crawler#20]
Log important events with time-stamps.
- [ ] move to, restore from archive ( #19 )
- [ ] number of updates loaded from a source
- [ ] number of updates loaded from a non-source ( #10 )
- [ ] errors
- [ ] add, remove a source ( #7 , what if sources were edited manually? don't log or compare with backup file?)
- [ ] split log if too long (how long?)
